#!/usr/bin/env bash

set -e

########### Add system
echo "# Generated by entrypoint.sh" > /etc/monit/conf.d/system.cfg

cat << EOF >> /etc/monit/conf.d/system.cfg
# Generated by entrypoint.sh
check system cpu
    if cpu usage (user) > 80% for 2 cycles then alert
    if cpu usage (system) > 20% for 2 cycles then alert
    if cpu usage (wait) > 80% for 2 cycles then alert
EOF
done

cat << EOF >> /etc/monit/conf.d/system.cfg
# Generated by entrypoint.sh
check system loadavg
    if loadavg (1min) > 3 then alert
    if loadavg (5min) > 2 then alert
    if loadavg (15min) > 1 then alert
EOF
done

cat << EOF >> /etc/monit/conf.d/system.cfg
# Generated by entrypoint.sh
check system memory
    if memory usage > 80% for 4 cycles then alert
EOF
done

cat << EOF >> /etc/monit/conf.d/system.cfg
# Generated by entrypoint.sh
check system swap
    if swap usage > 20% for 4 cycles then alert
EOF
done

########### Add all filesystems mounted
MOUNTS=$(df --output=target | tail -n +2)
echo "# Generated by entrypoint.sh" > /etc/monit/conf.d/filesystem.cfg

for M in $MOUNTS; do
    NAME=$(basename $M)
cat << EOF >> /etc/monit/conf.d/filesystem.cfg
check filesystem ${NAME} with path ${M}
  if space usage > 80% for 5 times within 15 cycles then alert
EOF
done

########### Add all interface network
INTERFACES=$(ifconfig | cut -c 1-8 | sort | uniq -u)
echo "# Generated by entrypoint.sh" > /etc/monit/conf.d/network.cfg

for I in $INTERFACES; do
    NAME=$(basename $I)
cat << EOF >> /etc/monit/conf.d/network.cfg
check network ${NAME} with interface ${I}
  if saturation > 90% then alert
  if upload > 500 kB/s then alert
  if total downloaded > 1 GB in last 2 hours then alert
  if total downloaded > 10 GB in last day then alert
EOF
done

exec "$@"