#!/bin/sh

MONIT_USERNAME=${MONIT_USERNAME:-admin}
MONIT_PASSWORD=${MONIT_PASSWORD:-changeit}

echo "# Generated by entrypoint.sh" > /etc/monit/monit.d/1_httpd.cfg

cat << EOF >> /etc/monit/monit.d/1_httpd.cfg
# Generated by entrypoint.sh
set httpd
    port 2812
    allow 127.0.0.1
    allow "::1"
    allow ${MONIT_USERNAME}:${MONIT_PASSWORD}
EOF
