#!/bin/sh

# -------------------------------------
# CHECK THAT AUTH VARIABLES ARE DEFINED
# -------------------------------------
if [ -z "$MONIT_USERNAME" ]; then
    echo "You must define MONIT_USERNAME"
    exit 1
fi

if [ -z "$MONIT_PASSWORD" ]; then
    echo "You must define MONIT_PASSWORD"
    exit 1
fi

if [ -z "$MONIT_DELAY" ]; then
    MONIT_DELAY=0
fi

# -----------------------------------------------
# CONFIGURATION
# Author Yoann Vanitou <yvanitou@gmail.com>
# Category Script
# Version  20171206
# -----------------------------------------------
LOCK=/.lock

if [ ! -f "$LOCK" ]; then

    chmod 600 /etc/monitrc/monitrc

cat << EOF > /etc/monitrc/monit.d/1_httpd.cfg
# Generated by docker-entrypoint.sh
set httpd
    port 2812
    allow 127.0.0.1
    allow "::1"
    allow ${MONIT_USERNAME}:${MONIT_PASSWORD}
EOF

    if [ $MONIT_DELAY -gt 0 ]; then
        sleep $MONIT_DELAY
    fi

    # --------------
    # ADD ALL SCRIPT
    # --------------
    if [ -d /docker-entrypoint.d ]; then
        for f in /docker-entrypoint.d/*; do
            [ -x "$f" ] && . "$f"
        done
        unset f
    fi

    touch $LOCK
fi

exec "$@"
