#!/bin/bash

# -------------------------------------
# CHECK THAT AUTH VARIABLES ARE DEFINED
# -------------------------------------
if [ -z "$MONIT_USERNAME" ]; then
    echo "You must define MONIT_USERNAME"
    exit 1
fi

if [ -z "$MONIT_PASSWORD" ]; then
    echo "You must define MONIT_PASSWORD"
    exit 1
fi

# -----------------------------------------------
# LOGIN CONFIGURATION
# Author Yoann Vanitou <yvanitou@gmail.com>
# Category Script
# Version  20171206
# -----------------------------------------------
cat << EOF > /usr/local/etc/monitrc/monit.d/1_httpd.cfg
# Generated by docker-entrypoint.sh
set httpd
    port 2812
    allow 127.0.0.1
    allow 10.42.0.0/8 readonly
    allow ${MONIT_USERNAME}:${MONIT_PASSWORD}
EOF

# --------------
# ADD ALL SCRIPT
# --------------
if [ -d /docker-entrypoint.d ]; then
    for f in /docker-entrypoint.d/*; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

echo "Running $@"
exec "$@"
